on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: Typescript autocompile dist
jobs:
  tsc-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: rm ./dist
      - run: npm install
      - run: npm install -g typescript
      - run: tsc
